package listaCircularGeneric;

public class Principal extends javax.swing.JFrame {
    private FrameListaCircularLibros modLibro;
    private FrameListaCircularRevista modRevista;
    private FrameListaCircularLibros modArticulo;


    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        setSize(1200,800);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        jToolBar1 = new javax.swing.JToolBar();
        btn_libro = new javax.swing.JButton();
        btn_revista = new javax.swing.JButton();
        btn_articulo = new javax.swing.JButton();
        dpn_escritorio = new javax.swing.JDesktopPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jToolBar1.setRollover(true);

        btn_libro.setIcon(new javax.swing.ImageIcon(""));
        //btn_arreglo.setIcon(new javax.swing.ImageIcon("C:\\Users\\PC\\Desktop\\iconos\\array_icon.png")); // NOI18N
        btn_libro.setText("Libro");
        btn_libro.setFocusable(false);
        btn_libro.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_libro.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_libro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_libroActionPerformed(evt);
            }
        });
        jToolBar1.add(btn_libro);

        btn_revista.setIcon(new javax.swing.ImageIcon("")); // NOI18N
        btn_revista.setText("Revista");
        btn_revista.setFocusable(false);
        btn_revista.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_revista.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_revista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt){
                btn_revistaActionPerformed(evt);
            }

        });
        jToolBar1.add(btn_revista);

        btn_articulo.setIcon(new javax.swing.ImageIcon("")); // NOI18N
        btn_articulo.setText("Articulo");
        btn_articulo.setToolTipText("");
        btn_articulo.setFocusable(false);
        btn_articulo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_articulo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_articulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_articuloActionPerformed(evt);
            }
        });
        jToolBar1.add(btn_articulo);


        getContentPane().add(jToolBar1, java.awt.BorderLayout.PAGE_START);
        getContentPane().add(dpn_escritorio, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_libroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_filaActionPerformed
        modLibro = new FrameListaCircularLibros();
        dpn_escritorio.add(modLibro);
    }//GEN-LAST:event_btn_filaActionPerformed

    private void btn_revistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_arregloActionPerformed
        modRevista = new FrameListaCircularRevista();
        dpn_escritorio.add(modRevista);
    }//GEN-LAST:event_btn_arregloActionPerformed

    private void btn_articuloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_pilaActionPerformed
        modArticulo = new FrameListaCircularLibros();
        dpn_escritorio.add(modArticulo);
    }//GEN-LAST:event_btn_pilaActionPerformed


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(recopiladorU2.Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(recopiladorU2.Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(recopiladorU2.Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(recopiladorU2.Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_libro;
    private javax.swing.JButton btn_revista;
    private javax.swing.JButton btn_articulo;
    private javax.swing.JDesktopPane dpn_escritorio;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables


}


