package recopiladorU2;

import java.awt.event.ActionEvent;
import colas.*;

import javax.swing.*;

public class JIFColas extends javax.swing.JInternalFrame {

    private ColaProceso cola;

    /**
     * Creates new form JIFila
     */
    public JIFColas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblIsbn = new javax.swing.JLabel();
        lblTitulo = new javax.swing.JLabel();
        lblAutor = new javax.swing.JLabel();
        txtFIsbn = new javax.swing.JTextField();
        txtFTitulo = new javax.swing.JTextField();
        txtFAutor = new javax.swing.JTextField();
        jTextArea1 = new javax.swing.JTextArea();
        btnCrear = new javax.swing.JButton();
        btnEncolar = new javax.swing.JButton();
        btnDesencolar = new javax.swing.JButton();
        btnMostrarCabeza = new javax.swing.JButton();
        btnMostrarCola = new javax.swing.JButton();
        btnVaciar = new javax.swing.JButton();
        btnDestruir = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("C O L A S");
        setVisible(true);

        lblIsbn.setText("ISBN:");

        lblTitulo.setText("TITULO:");

        lblAutor.setText("AUTOR:");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);

        btnCrear.setText("Crear");

        btnEncolar.setText("Encolar");

        btnDesencolar.setText("Desencolar");

        btnMostrarCabeza.setText("Mostrar Cabeza");

        btnMostrarCola.setText("Mostrar Cola");

        btnVaciar.setText("Vaciar Cola");

        btnDestruir.setText("Destruir Cola");

        btnCrear.addActionListener(new java.awt.event.ActionListener(){
            @Override
            public void actionPerformed(ActionEvent evt) {
                btnCrearActionPerformed(evt);
            }
        });

        btnEncolar.addActionListener(new java.awt.event.ActionListener(){
            @Override
            public void actionPerformed(ActionEvent evt) {
                btnEncolarActionPerformed(evt);
            }
        });

        btnDesencolar.addActionListener(new java.awt.event.ActionListener(){
            @Override
            public void actionPerformed(ActionEvent evt) {
                btnDesencolarActionPerformed(evt);
            }
        });

        btnMostrarCabeza.addActionListener(new java.awt.event.ActionListener(){
            @Override
            public void actionPerformed(ActionEvent evt) {
                btnMostrarCabezaActionPerformed(evt);
            }
        });

        btnMostrarCola.addActionListener(new java.awt.event.ActionListener(){
            @Override
            public void actionPerformed(ActionEvent evt) {
                btnMostrarColaActionPerformed(evt);
            }
        });

        btnVaciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVaciarActionPerformed(evt);
            }
        });

        btnDestruir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDestruirActionPerformed(evt);
            }
        });

        getContentPane().setLayout(null);

        lblIsbn.setBounds(50,30,150,25);
        txtFIsbn.setBounds(100,30,250,25);
        add(lblIsbn);
        add(txtFIsbn);
        lblTitulo.setBounds(40,65,150,25);
        txtFTitulo.setBounds(100,65,250,25);
        add(lblTitulo);
        add(txtFTitulo);
        lblAutor.setBounds(40,100,150,25);
        txtFAutor.setBounds(100,100,250,25);
        add(lblAutor);
        add(txtFAutor);

        jTextArea1.setBounds(40,150,410,300);

        btnCrear.setBounds(500,30,150,25);
        btnEncolar.setBounds(500,70,150,25);
        btnDesencolar.setBounds(500,110,150,25);
        btnMostrarCabeza.setBounds(500,150,150,25);
        btnMostrarCola.setBounds(500,190,150,25);
        btnVaciar.setBounds(500,230,150,25);
        btnDestruir.setBounds(500,270,150,25);

        add(jTextArea1);
        add(btnCrear);
        add(btnEncolar);
        add(btnDesencolar);
        add(btnMostrarCabeza);
        add(btnMostrarCola);
        add(btnVaciar);
        add(btnDestruir);


        getContentPane().setSize(700,500);
        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCrearActionPerformed(java.awt.event.ActionEvent evt){
        if (cola == null){
            cola = new MiColaProceso();
            jTextArea1.append("Cola creada con exito.\n");
        } else {
            JOptionPane.showMessageDialog(null,"La cola ya ha sido creada.");
        }

    }

    private void btnEncolarActionPerformed(java.awt.event.ActionEvent evt) {
        if(cola == null){
            JOptionPane.showMessageDialog(null,"Debe crear la cola primero.");
        }else {

            String sIsbn = JOptionPane.showInputDialog("Titulo:");

            /*
            sc.nextLine();
            System.out.println("Ingrese el titulo: ");
            titulo = sc.nextLine();
            System.out.println("ingrese el autor: ");
            autor = sc.nextLine();
            System.out.println("Ingresa el codigo del libro");
            isbn = sc.nextLine();

            // LOS COMENTE PORQUE MODIFIQUE LA CLASE TRABAJO
            //Trabajo trabajo = new Trabajo(titulo, autor,isbn);
            //cola.encolar(trabajo);

             */
        }
    }

    private void btnDesencolarActionPerformed(java.awt.event.ActionEvent evt) {

    }

    private void btnMostrarCabezaActionPerformed(java.awt.event.ActionEvent evt){

    }
    private void btnMostrarColaActionPerformed(java.awt.event.ActionEvent evt){

    }
    private void btnVaciarActionPerformed(java.awt.event.ActionEvent evt){

    }
    private void btnDestruirActionPerformed(java.awt.event.ActionEvent evt){

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCrear;
    private javax.swing.JButton btnEncolar;
    private javax.swing.JButton btnDesencolar;
    private javax.swing.JButton btnMostrarCabeza;
    private javax.swing.JButton btnMostrarCola;
    private javax.swing.JButton btnVaciar;
    private javax.swing.JButton btnDestruir;
    private javax.swing.JLabel lblCrearCola;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblAutor;
    private javax.swing.JLabel lblIsbn;
    private javax.swing.JTextField txtFTitulo;
    private javax.swing.JTextField txtFAutor;
    private javax.swing.JTextField txtFIsbn;

    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}

