package recopiladorU2;

public class JIFila extends javax.swing.JInternalFrame {

    /**
     * Creates new form JIFila
     */
    public JIFila() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCrearFila = new javax.swing.JLabel();
        lblEncolar = new javax.swing.JLabel();
        lblDesencolar = new javax.swing.JLabel();
        lblMostrarCabeza = new javax.swing.JLabel();
        lblMostrarFila = new javax.swing.JLabel();
        lblVaciarFila = new javax.swing.JLabel();
        lblDestruirFila = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        btnCrear = new javax.swing.JButton();
        btnEncolar = new javax.swing.JButton();
        btnDesencolar = new javax.swing.JButton();
        btnMostrarCabeza = new javax.swing.JButton();
        btnMostrarFila = new javax.swing.JButton();
        btnVaciar = new javax.swing.JButton();
        btnDestruir = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("F I L A S");
        setVisible(true);

        lblCrearFila.setText("Crear Fila");

        lblEncolar.setText("Encolar");

        lblDesencolar.setText("Desencolar");

        lblMostrarCabeza.setText("Mostrar cabeza de fila");

        lblMostrarFila.setText("Mostrar Fila");

        lblVaciarFila.setText("Vaciar Fila");

        lblDestruirFila.setText("Destruir Fila");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        btnCrear.setText("Crear");

        btnEncolar.setText("Encolar");

        btnDesencolar.setText("Desencolar");

        btnMostrarCabeza.setText("Mostrar Cabeza");

        btnMostrarFila.setText("Mostrar Fila");

        btnVaciar.setText("Vaciar Fila");
        btnVaciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        btnDestruir.setText("Destruir Fila");
        btnDestruir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblDestruirFila)
                                        .addComponent(lblVaciarFila)
                                        .addComponent(lblMostrarFila)
                                        .addComponent(lblMostrarCabeza)
                                        .addComponent(lblDesencolar)
                                        .addComponent(lblEncolar)
                                        .addComponent(lblCrearFila))
                                .addGap(52, 52, 52)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 482, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(btnCrear, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(btnEncolar, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(btnDesencolar, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(btnMostrarCabeza, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(btnMostrarFila, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(btnVaciar, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(btnDestruir, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addContainerGap())
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(65, 65, 65)
                                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(52, 52, 52)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(btnCrear)
                                                                .addGap(28, 28, 28)
                                                                .addComponent(btnEncolar)
                                                                .addGap(27, 27, 27)
                                                                .addComponent(btnDesencolar)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(btnMostrarCabeza)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(btnMostrarFila)
                                                                .addGap(28, 28, 28)
                                                                .addComponent(btnVaciar)
                                                                .addGap(47, 47, 47)
                                                                .addComponent(btnDestruir))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(lblCrearFila)
                                                                .addGap(31, 31, 31)
                                                                .addComponent(lblEncolar)
                                                                .addGap(30, 30, 30)
                                                                .addComponent(lblDesencolar)
                                                                .addGap(30, 30, 30)
                                                                .addComponent(lblMostrarCabeza)
                                                                .addGap(27, 27, 27)
                                                                .addComponent(lblMostrarFila)
                                                                .addGap(47, 47, 47)
                                                                .addComponent(lblVaciarFila)
                                                                .addGap(43, 43, 43)
                                                                .addComponent(lblDestruirFila)))))
                                .addContainerGap(177, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCrear;
    private javax.swing.JButton btnEncolar;
    private javax.swing.JButton btnDesencolar;
    private javax.swing.JButton btnMostrarCabeza;
    private javax.swing.JButton btnMostrarFila;
    private javax.swing.JButton btnVaciar;
    private javax.swing.JButton btnDestruir;
    private javax.swing.JLabel lblCrearFila;
    private javax.swing.JLabel lblEncolar;
    private javax.swing.JLabel lblDesencolar;
    private javax.swing.JLabel lblMostrarCabeza;
    private javax.swing.JLabel lblMostrarFila;
    private javax.swing.JLabel lblVaciarFila;
    private javax.swing.JLabel lblDestruirFila;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}

