package recopiladorU2;

import pilas.*;
import javax.swing.JOptionPane;

public class JIFPila extends javax.swing.JInternalFrame {

    private Pila pila;
    /**
     * Creates new form JIFPila
     */
    public JIFPila() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("P I L A S");
        setVisible(true);

        jLabel1.setText("Crear pila");

        jLabel2.setText("Apilar");

        jLabel3.setText("Desapilar");

        jLabel4.setText("obtener cima");

        jLabel5.setText("mostrar pila");

        jLabel6.setText("vaciar pila");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jButton1.setText("Crear Pila");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Apilar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("desapilar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("obtener");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("mostrar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("Vaciar");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jLabel7.setText("destruir pila");

        jButton7.setText("Destruir");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(54, 54, 54)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel1)
                                        .addComponent(jLabel6)
                                        .addComponent(jLabel5)
                                        .addComponent(jLabel3)
                                        .addComponent(jLabel2)
                                        .addComponent(jLabel4)
                                        .addComponent(jLabel7))
                                .addGap(62, 62, 62)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jButton7)
                                        .addComponent(jButton6)
                                        .addComponent(jButton4)
                                        .addComponent(jButton3)
                                        .addComponent(jButton5)
                                        .addComponent(jButton2)
                                        .addComponent(jButton1))
                                .addContainerGap(28, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(48, 48, 48)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(jButton1)
                                                .addGap(18, 18, 18)
                                                .addComponent(jButton2)
                                                .addGap(28, 28, 28)
                                                .addComponent(jButton3)
                                                .addGap(31, 31, 31)
                                                .addComponent(jButton4)
                                                .addGap(26, 26, 26)
                                                .addComponent(jButton5)
                                                .addGap(26, 26, 26)
                                                .addComponent(jButton6)
                                                .addGap(18, 18, 18)
                                                .addComponent(jButton7))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addGroup(layout.createSequentialGroup()
                                                        .addComponent(jLabel1)
                                                        .addGap(32, 32, 32)
                                                        .addComponent(jLabel2)
                                                        .addGap(27, 27, 27)
                                                        .addComponent(jLabel3)
                                                        .addGap(26, 26, 26)
                                                        .addComponent(jLabel4)
                                                        .addGap(31, 31, 31)
                                                        .addComponent(jLabel5)
                                                        .addGap(32, 32, 32)
                                                        .addComponent(jLabel6)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(jLabel7))
                                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(152, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        destruirPila();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        crearPila();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        apilarElemento();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        desapilarElemento();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        obtenerCima();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        mostrarPila();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        vaciarPila();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void crearPila() {
        if (pila == null) {
            pila = new MiPila();
            jTextArea1.append("Pila creada.\n");
        } else {
            jTextArea1.append("La pila ya existe.\n");
        }
    }

    private void apilarElemento() {
        if (pila == null) {
            jTextArea1.append("Primero debe crear la pila.\n");
        } else {
            String urlInput = JOptionPane.showInputDialog("Ingrese la URL:");
            if (urlInput != null && !urlInput.trim().isEmpty()) {
                URL nuevaURL = new URL(urlInput);
                pila.apilar(nuevaURL);
                jTextArea1.append("Elemento apilado: " + urlInput + "\n");
            }
        }
    }

    private void desapilarElemento() {
        if (pila == null || pila.vacia()) {
            jTextArea1.append("La pila está vacía o no ha sido creada.\n");
        } else {
            pila.desapilar();
            jTextArea1.append("Elemento desapilado.\n");
        }
    }

    private void obtenerCima() {
        if (pila == null || pila.vacia()) {
            jTextArea1.append("La pila está vacía o no ha sido creada.\n");
        } else {
            URL cima = pila.obtener();
            jTextArea1.append("Cima de la pila: " + cima.getUrl() + "\n");
        }
    }

    private void mostrarPila() {
        if (pila == null || pila.vacia()) {
            jTextArea1.append("La pila está vacía o no ha sido creada.\n");
        } else {
            jTextArea1.append("Elementos de la pila:\n");
            Pila tempPila = new MiPila();
            while (!pila.vacia()) {
                URL url = pila.obtener();
                jTextArea1.append(url.getUrl() + "\n");
                tempPila.apilar(url);
                pila.desapilar();
            }
            while (!tempPila.vacia()) {
                pila.apilar(tempPila.obtener());
                tempPila.desapilar();
            }
        }
    }

    private void vaciarPila() {
        if (pila == null || pila.vacia()) {
            jTextArea1.append("La pila está vacía o no ha sido creada.\n");
        } else {
            while (!pila.vacia()) {
                pila.desapilar();
            }
            jTextArea1.append("Pila vaciada.\n");
        }
    }

    private void destruirPila() {
        if (pila == null) {
            jTextArea1.append("La pila no existe.\n");
        } else {
            pila = null;
            jTextArea1.append("Pila destruida.\n");
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}

