package recopiladorU2;

import javax.swing.*;

public class Principal extends javax.swing.JFrame {

    private JIFArreglo modArreglo;
    private JIFPila modPila;
    private JIFLista modLista;
    private JIFListaDoble modListaDoble;
    private JIFListaCircular modListaCircular;
    private JIFila modFila;


    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        btn_arreglo = new javax.swing.JButton();
        btn_fila = new javax.swing.JButton();
        btn_pila = new javax.swing.JButton();
        btn_simple = new javax.swing.JButton();
        btn_doble = new javax.swing.JButton();
        btn_circular = new javax.swing.JButton();
        dpn_escritorio = new javax.swing.JDesktopPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jToolBar1.setRollover(true);

        btn_arreglo.setIcon(new javax.swing.ImageIcon("C:\\Users\\PC\\Desktop\\iconos\\array_icon.png")); // NOI18N
        btn_arreglo.setText("Arreglo");
        btn_arreglo.setFocusable(false);
        btn_arreglo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_arreglo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_arreglo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_arregloActionPerformed(evt);
            }
        });
        jToolBar1.add(btn_arreglo);

        btn_fila.setIcon(new javax.swing.ImageIcon("C:\\Users\\PC\\Desktop\\iconos\\fila.png")); // NOI18N
        btn_fila.setText("Fila");
        btn_fila.setFocusable(false);
        btn_fila.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_fila.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_fila.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_filaActionPerformed(evt);
            }
        });
        jToolBar1.add(btn_fila);

        btn_pila.setIcon(new javax.swing.ImageIcon("C:\\Users\\PC\\Desktop\\iconos\\pila.png")); // NOI18N
        btn_pila.setText("Pila");
        btn_pila.setToolTipText("");
        btn_pila.setFocusable(false);
        btn_pila.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_pila.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_pila.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_pilaActionPerformed(evt);
            }
        });
        jToolBar1.add(btn_pila);

        btn_simple.setIcon(new javax.swing.ImageIcon("C:\\Users\\PC\\Desktop\\iconos\\lista simple.png")); // NOI18N
        btn_simple.setText("Lista Simple");
        btn_simple.setFocusable(false);
        btn_simple.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_simple.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_simple.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_simpleActionPerformed(evt);
            }
        });
        jToolBar1.add(btn_simple);

        btn_doble.setIcon(new javax.swing.ImageIcon("C:\\Users\\PC\\Desktop\\iconos\\lista doble.png")); // NOI18N
        btn_doble.setText("Lista Doble");
        btn_doble.setFocusable(false);
        btn_doble.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_doble.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_doble.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_dobleActionPerformed(evt);
            }
        });
        jToolBar1.add(btn_doble);

        btn_circular.setIcon(new javax.swing.ImageIcon("C:\\Users\\PC\\Desktop\\iconos\\lista circular.png")); // NOI18N
        btn_circular.setText("Lista Circular");
        btn_circular.setFocusable(false);
        btn_circular.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_circular.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_circular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_circularActionPerformed(evt);
            }
        });
        jToolBar1.add(btn_circular);

        getContentPane().add(jToolBar1, java.awt.BorderLayout.PAGE_START);
        getContentPane().add(dpn_escritorio, java.awt.BorderLayout.CENTER);


        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_filaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_filaActionPerformed
        modFila = new JIFila();
        dpn_escritorio.add(modFila);
    }//GEN-LAST:event_btn_filaActionPerformed

    private void btn_arregloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_arregloActionPerformed
        modArreglo = new JIFArreglo();
        dpn_escritorio.add(modArreglo);
    }//GEN-LAST:event_btn_arregloActionPerformed

    private void btn_pilaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_pilaActionPerformed
        modPila = new JIFPila();
        dpn_escritorio.add(modPila);
    }//GEN-LAST:event_btn_pilaActionPerformed

    private void btn_simpleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_simpleActionPerformed
        modLista = new JIFLista();
        dpn_escritorio.add(modLista);
    }//GEN-LAST:event_btn_simpleActionPerformed

    private void btn_dobleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_dobleActionPerformed
        modListaDoble = new JIFListaDoble();
        dpn_escritorio.add(modListaDoble);
    }//GEN-LAST:event_btn_dobleActionPerformed

    private void btn_circularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_circularActionPerformed
        modListaCircular = new JIFListaCircular();
        dpn_escritorio.add(modListaCircular);
    }//GEN-LAST:event_btn_circularActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_arreglo;
    private javax.swing.JButton btn_circular;
    private javax.swing.JButton btn_doble;
    private javax.swing.JButton btn_fila;
    private javax.swing.JButton btn_pila;
    private javax.swing.JButton btn_simple;
    private javax.swing.JDesktopPane dpn_escritorio;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables


}

